[package]
name = "yew-rust-example"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml", "yaml", "msgpack", "cbor"] }